### ISSUE TITLE
Add document attribute to point to `metanorma.yml`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-generic#19]
A user may have multiple `metanorma.yml` files or a single one located outside the current directory.

The goal is to allow the user to do:

```adoc
= My title
:customize: /Users/me/mn/organization-1.yml
..
```

And Metanorma Acme will ignore the local `metanorma.yml`.

**Comment by w00lf** [comment]
@ronaldtse should i delete customization by default on gem initialization? Currently, when the user initializes metanorma-acme gem it will try to search a file called `metanorma.yml` in the current directory and if it succeeds its values. Should it only use `customize` directive explicitly?

**Comment by opoudjis** [comment]
Documenting in metanorma.com
