### ISSUE TITLE
Metanorma simple adoption not working

### ISSUE THREAD

**Issue by christophenoel** [metanorma/metanorma-generic#72]
Hello guys,

I have spent a lot of time for customizing via YAML the metanorma-generic flavor (because we don't want to program anything). The metanorma.yml seems not parsed and I can't find any further guidance in the documentation.

1. Our file `report1/document.adoc` includes `:mn-document-class: generic`
2. I added file `report1/metanorma.yml` with content from `https://github.com/metanorma/metanorma-generic/blob/main/metanorma.yml.example` and modified some fields (e.g., organization_name_long) 
3. I built the doc with latest docker image (tried with metanorma site and metanorma compile).
Example: `docker run -v "d:\mydir":/metanorma metanorma/mn metanorma site generate --agree-to-terms`

The metanorma.yml file (not the collection configuration, but the one in the report) is ignored. The documentation does not clarify the second approach with "Metanorma::Generic.configuration method" (where should be provided this config ?).

Could you please provide some tips for solving this problem ?

Thank you very much.

**Comment by opoudjis** [comment]
Sorry for delay. The intent was to customise the generic gem (as is done e.g. in metanorma-ribose), but let me investigate what is happening. But for starters: metanorma-generic only processes the metanorma.yml file inside of the gem, it does not process an externally located metanorma.yml.

````
@yaml = File.join(File.dirname(self.class::_file || __FILE__), "..",
                          "..", YAML_CONFIG_FILE)
````

So our presupposition has been that you will copy metanorma.yml.example to metanorma.yml, and recompile the gem. (In fact, our presupposition has been that you would inherit from the gem into a new gem.)

I realise that isn't a zero coding solution! I can alter the code to look for the configuration file in the same location as the document, as you propose to do, but I won't get to this for at least a couple of weeks.

**Comment by opoudjis** [comment]
Actually, I'd forgotten this, but it turns out we have already addressed this issue, by allowing you to specify a YAML configuration file in the document, using a `:customize:` document attribute:

https://www.metanorma.org/builder/topics/simple-adoption/
