### ISSUE TITLE
There is currently no mn-samples-generic repository

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-generic#76]
https://github.com/metanorma/metanorma-generic/actions/runs/4654810188/jobs/8236867757

**Comment by CAMOBAP** [comment]
Fixed https://github.com/metanorma/ci/commit/61338027db955ed857e0ac7312fba01139b0a3e3 retrying CI

**Comment by CAMOBAP** [comment]
Waiting for https://github.com/metanorma/metanorma-generic/actions/runs/4654810188/jobs/8238513653

**Comment by CAMOBAP** [comment]
The fix confirmed https://github.com/metanorma/metanorma-generic/actions/runs/4772614868/jobs/8485228943#step:4:43

> No .github/workflows/samples-matrix-part.json or https://github.com/metanorma/mn-samples-generic found!
> Commit .github/workflows/samples-matrix-part.json or pass custom file in samples-matrix-json-file
